"""
SQLAlchemy ORM Models

Defines the relational schema for users, conversations, participants, messages,
and refresh tokens stored in PostgreSQL.
"""

from sqlalchemy import Boolean, Column, ForeignKey, Integer, String, DateTime, Text, Enum
from sqlalchemy.orm import relationship
from datetime import datetime, timezone
import enum

from app.db.session import Base

class FriendshipStatus(str, enum.Enum):
    """Enumeration of friendship states."""
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    BLOCKED = "BLOCKED"

class Friendship(Base):
    """
    Friendship Model.
    
    Represents the social graph edges (friends, blocks, requests).
    """
    __tablename__ = "friendships"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    friend_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    status = Column(Enum(FriendshipStatus), default=FriendshipStatus.PENDING, nullable=False)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc).replace(tzinfo=None))
    updated_at = Column(
        DateTime,
        default=lambda: datetime.now(timezone.utc).replace(tzinfo=None),
        onupdate=lambda: datetime.now(timezone.utc).replace(tzinfo=None)
    )

    # Relationships
    user = relationship("User", foreign_keys=[user_id])
    friend = relationship("User", foreign_keys=[friend_id])

class MessageStatus(str, enum.Enum):
    """Enumeration of message delivery and read states."""
    SENT = "SENT"            # Persisted to server database and acknowledged to sender
    DELIVERED = "DELIVERED"  # Pushed to recipient WebSocket
    READ = "READ"            # Rendered and acknowledged by recipient

class User(Base):
    """
    User Account Model.

    Stores registration credentials, profile customization (nickname, avatar color),
    and real-time connection presence status.
    """
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    username = Column(String, unique=True, index=True, nullable=False)
    nickname = Column(String, nullable=False)
    email = Column(String, unique=True, index=True, nullable=False)
    hashed_password = Column(String, nullable=False)
    avatar_color = Column(String, nullable=False)
    avatar_url = Column(String, nullable=True)
    bio = Column(Text, nullable=True)
    status_message = Column(String, nullable=True)
    privacy = Column(String, default="PUBLIC") # Can be PUBLIC, PRIVATE
    is_online = Column(Boolean, default=False)
    last_seen = Column(DateTime, default=lambda: datetime.now(timezone.utc).replace(tzinfo=None))
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc).replace(tzinfo=None))

    # Relationships
    participants = relationship("ConversationParticipant", back_populates="user")
    messages = relationship("Message", back_populates="sender")

class Conversation(Base):
    """
    Conversation Thread Model.

    Represents a 1-on-1 direct message or multi-user group chat room.
    """
    __tablename__ = "conversations"

    id = Column(Integer, primary_key=True, index=True)
    is_group = Column(Boolean, default=False)
    name = Column(String, nullable=True)  # Optional display title for group chats
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc).replace(tzinfo=None))
    updated_at = Column(
        DateTime,
        default=lambda: datetime.now(timezone.utc).replace(tzinfo=None),
        onupdate=lambda: datetime.now(timezone.utc).replace(tzinfo=None)
    )

    # Relationships
    participants = relationship("ConversationParticipant", back_populates="conversation")
    messages = relationship("Message", back_populates="conversation")

class ConversationParticipant(Base):
    """
    Association table joining Users and Conversations.
    """
    __tablename__ = "conversation_participants"

    conversation_id = Column(Integer, ForeignKey("conversations.id"), primary_key=True)
    user_id = Column(Integer, ForeignKey("users.id"), primary_key=True)
    joined_at = Column(DateTime, default=lambda: datetime.now(timezone.utc).replace(tzinfo=None))

    # Relationships
    conversation = relationship("Conversation", back_populates="participants")
    user = relationship("User", back_populates="participants")

class Message(Base):
    """
    Chat Message Model.

    Stores message content, unique client idempotency token, sender reference,
    and lifecycle status (SENT, DELIVERED, READ).
    """
    __tablename__ = "messages"

    id = Column(Integer, primary_key=True, index=True)
    client_message_id = Column(String, unique=True, index=True, nullable=True)  # UUID generated by client
    conversation_id = Column(Integer, ForeignKey("conversations.id"), index=True, nullable=False)
    sender_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    content = Column(Text, nullable=False)
    status = Column(Enum(MessageStatus), default=MessageStatus.SENT)
    created_at = Column(DateTime, index=True, default=lambda: datetime.now(timezone.utc).replace(tzinfo=None))

    # Relationships
    conversation = relationship("Conversation", back_populates="messages")
    sender = relationship("User", back_populates="messages")

class RefreshToken(Base):
    """
    Persistent Refresh Token Model.

    Stores cryptographically secure tokens issued in HttpOnly cookies, supporting revocation upon logout/rotation.
    """
    __tablename__ = "refresh_tokens"

    id = Column(Integer, primary_key=True, index=True)
    token = Column(String, unique=True, index=True, nullable=False)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    expires_at = Column(DateTime, nullable=False)
    is_revoked = Column(Boolean, default=False)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc).replace(tzinfo=None))

    # Relationship
    user = relationship("User")

