"""Add client_message_id

Revision ID: 1fd60ee41c0c
Revises: 448c62e2be73
Create Date: 2026-08-21 16:00:30.980952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fd60ee41c0c'
down_revision: Union[str, Sequence[str], None] = '448c62e2be73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('client_message_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_messages_client_message_id'), 'messages', ['client_message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_client_message_id'), table_name='messages')
    op.drop_column('messages', 'client_message_id')
    # ### end Alembic commands ###
