"""Add media fields to Message model

Revision ID: c049e05a61fe
Revises: 3eca419a4d06
Create Date: 2026-08-22 23:59:46.969959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c049e05a61fe'
down_revision: Union[str, Sequence[str], None] = '3eca419a4d06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('media_url', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('media_type', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('media_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'media_size')
    op.drop_column('messages', 'media_type')
    op.drop_column('messages', 'media_url')
    # ### end Alembic commands ###
