"""
Pydantic Validation and Serialization Schemas

Defines request validation and response models for users, auth tokens,
messages, conversations, and cursor-based pagination envelopes.
"""

from pydantic import BaseModel, EmailStr, Field, field_validator
from datetime import datetime
from typing import Optional, List
import re

class UserBase(BaseModel):
    """Base user fields shared across creation and responses."""
    username: str = Field(..., min_length=3, max_length=15, pattern=r'^[a-zA-Z0-9]+$')
    nickname: str
    email: EmailStr

class UserCreate(UserBase):
    """User registration schema with strict password complexity requirements."""
    password: str = Field(..., min_length=8)

    @field_validator('password')
    def password_complexity(cls, v):
        """Validates that password is alphanumeric and includes at least one uppercase letter."""
        if not re.match(r'^[a-zA-Z0-9]+$', v):
            raise ValueError("Password must be alphanumeric")
        if not any(char.isupper() for char in v):
            raise ValueError("Password must contain at least one uppercase letter")
        return v

class UserResponse(UserBase):
    """Full user profile response for the authenticated user."""
    id: int
    avatar_color: str
    avatar_url: Optional[str] = None
    bio: Optional[str] = None
    status_message: Optional[str] = None
    privacy: str
    is_online: bool
    last_seen: datetime
    created_at: datetime

    model_config = {"from_attributes": True}

class PublicUserResponse(BaseModel):
    """Minimal, privacy-safe user profile embedded in conversations (excludes email)."""
    id: int
    username: str
    nickname: str
    avatar_color: str
    avatar_url: Optional[str] = None
    bio: Optional[str] = None
    status_message: Optional[str] = None
    is_online: bool
    last_seen: datetime

    model_config = {"from_attributes": True}

class FriendshipResponse(BaseModel):
    """Information about a friendship connection."""
    id: int
    user_id: int
    friend: PublicUserResponse
    status: str
    created_at: datetime
    updated_at: datetime

    model_config = {"from_attributes": True}

class UserProfileUpdate(BaseModel):
    """Fields that a user can update on their profile."""
    nickname: Optional[str] = None
    bio: Optional[str] = None
    status_message: Optional[str] = None
    privacy: Optional[str] = None

class ChangePasswordRequest(BaseModel):
    """Schema for updating a user's password."""
    current_password: str
    new_password: str = Field(..., min_length=8)

    @field_validator('new_password')
    def password_complexity(cls, v):
        """Validates that password is alphanumeric and includes at least one uppercase letter."""
        if not re.match(r'^[a-zA-Z0-9]+$', v):
            raise ValueError("Password must be alphanumeric")
        if not any(char.isupper() for char in v):
            raise ValueError("Password must contain at least one uppercase letter")
        return v

class Token(BaseModel):
    """JWT access token response model."""
    access_token: str
    token_type: str

class TokenData(BaseModel):
    """Decoded JWT payload subject container."""
    username: str | None = None

class GoogleTokenRequest(BaseModel):
    """Google OAuth ID token payload."""
    credential: str

class MessageCreate(BaseModel):
    """REST schema for message creation with client-supplied idempotency key."""
    content: str
    client_message_id: str = Field(..., description="Unique UUID generated by frontend for idempotency")

class MessageResponse(BaseModel):
    """Message payload returned to clients."""
    id: int
    client_message_id: Optional[str] = None
    conversation_id: int
    sender_id: int
    content: str
    status: str
    media_url: Optional[str] = None
    media_type: Optional[str] = None
    media_size: Optional[int] = None
    created_at: datetime

    model_config = {"from_attributes": True}

class MessagePage(BaseModel):
    """Paginated message envelope with cursor for infinite scrolling."""
    items: List[MessageResponse]
    next_cursor: Optional[str] = None

class ConversationParticipantResponse(BaseModel):
    """Participant information including joined timestamp and safe public user profile."""
    user: PublicUserResponse
    joined_at: datetime

    model_config = {"from_attributes": True}

class ConversationResponse(BaseModel):
    """Conversation summary with participants, timestamps, and optional latest message preview."""
    id: int
    is_group: bool
    name: Optional[str]
    created_at: datetime
    updated_at: datetime
    participants: List[ConversationParticipantResponse] = []
    latest_message: Optional[MessageResponse] = None
    unread_count: int = 0

    model_config = {"from_attributes": True}

